version: 2.1

jobs:
  create-eks-cluster:
    docker:
      - image: ubuntu:latest # Replace with the desired Terraform version
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Update apt package
          command: |
            apt-get update -y
      # Install AWS CLI (if not present in the Terraform image)
      - run:
          name: Install AWS CLI
          command: |
            apt-get update -y
            apt-get install -y python3-pip
            pip3 install --upgrade pip
            pip3 install awscli

      - run:
          name: Verify AWS CLI Installation
          command: aws --version

      - run:
          name: Install Git
          command: |
            apt-get update -y
            apt-get install -y git

      # Display Git version for verification
      - run:
          name: Verify Git installation
          command: git --version

      - run:
          name: Install Prerequisites
          command: |
            apt-get update && apt-get install -y unzip wget

      # Download and install Terraform
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            unzip terraform_1.0.0_linux_amd64.zip
            mv terraform /usr/local/bin/

      # Display Terraform version
      - run:
          name: Terraform Version
          command: terraform version
      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Apply Terraform changes to create EKS cluster
      - run:
          name: Terraform Plan
          command: terraform plan

workflows:
  create-eks:
    jobs:
      - create-eks-cluster
